/*
Copyright 2025 The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	dpmockv1alpha1 "volcano.sh/deviceplugin-mock/api/dpmock/v1alpha1"
)

// NodeResourceConfigurationLister helps list NodeResourceConfigurations.
// All objects returned here must be treated as read-only.
type NodeResourceConfigurationLister interface {
	// List lists all NodeResourceConfigurations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*dpmockv1alpha1.NodeResourceConfiguration, err error)
	// NodeResourceConfigurations returns an object that can list and get NodeResourceConfigurations.
	NodeResourceConfigurations(namespace string) NodeResourceConfigurationNamespaceLister
	NodeResourceConfigurationListerExpansion
}

// nodeResourceConfigurationLister implements the NodeResourceConfigurationLister interface.
type nodeResourceConfigurationLister struct {
	listers.ResourceIndexer[*dpmockv1alpha1.NodeResourceConfiguration]
}

// NewNodeResourceConfigurationLister returns a new NodeResourceConfigurationLister.
func NewNodeResourceConfigurationLister(indexer cache.Indexer) NodeResourceConfigurationLister {
	return &nodeResourceConfigurationLister{listers.New[*dpmockv1alpha1.NodeResourceConfiguration](indexer, dpmockv1alpha1.Resource("noderesourceconfiguration"))}
}

// NodeResourceConfigurations returns an object that can list and get NodeResourceConfigurations.
func (s *nodeResourceConfigurationLister) NodeResourceConfigurations(namespace string) NodeResourceConfigurationNamespaceLister {
	return nodeResourceConfigurationNamespaceLister{listers.NewNamespaced[*dpmockv1alpha1.NodeResourceConfiguration](s.ResourceIndexer, namespace)}
}

// NodeResourceConfigurationNamespaceLister helps list and get NodeResourceConfigurations.
// All objects returned here must be treated as read-only.
type NodeResourceConfigurationNamespaceLister interface {
	// List lists all NodeResourceConfigurations in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*dpmockv1alpha1.NodeResourceConfiguration, err error)
	// Get retrieves the NodeResourceConfiguration from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*dpmockv1alpha1.NodeResourceConfiguration, error)
	NodeResourceConfigurationNamespaceListerExpansion
}

// nodeResourceConfigurationNamespaceLister implements the NodeResourceConfigurationNamespaceLister
// interface.
type nodeResourceConfigurationNamespaceLister struct {
	listers.ResourceIndexer[*dpmockv1alpha1.NodeResourceConfiguration]
}
