/*
Copyright 2025 The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	dpmockv1alpha1 "volcano.sh/deviceplugin-mock/api/dpmock/v1alpha1"
	scheme "volcano.sh/deviceplugin-mock/client-go/clientset/versioned/scheme"
)

// NodeResourceConfigurationsGetter has a method to return a NodeResourceConfigurationInterface.
// A group's client should implement this interface.
type NodeResourceConfigurationsGetter interface {
	NodeResourceConfigurations(namespace string) NodeResourceConfigurationInterface
}

// NodeResourceConfigurationInterface has methods to work with NodeResourceConfiguration resources.
type NodeResourceConfigurationInterface interface {
	Create(ctx context.Context, nodeResourceConfiguration *dpmockv1alpha1.NodeResourceConfiguration, opts v1.CreateOptions) (*dpmockv1alpha1.NodeResourceConfiguration, error)
	Update(ctx context.Context, nodeResourceConfiguration *dpmockv1alpha1.NodeResourceConfiguration, opts v1.UpdateOptions) (*dpmockv1alpha1.NodeResourceConfiguration, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, nodeResourceConfiguration *dpmockv1alpha1.NodeResourceConfiguration, opts v1.UpdateOptions) (*dpmockv1alpha1.NodeResourceConfiguration, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*dpmockv1alpha1.NodeResourceConfiguration, error)
	List(ctx context.Context, opts v1.ListOptions) (*dpmockv1alpha1.NodeResourceConfigurationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *dpmockv1alpha1.NodeResourceConfiguration, err error)
	NodeResourceConfigurationExpansion
}

// nodeResourceConfigurations implements NodeResourceConfigurationInterface
type nodeResourceConfigurations struct {
	*gentype.ClientWithList[*dpmockv1alpha1.NodeResourceConfiguration, *dpmockv1alpha1.NodeResourceConfigurationList]
}

// newNodeResourceConfigurations returns a NodeResourceConfigurations
func newNodeResourceConfigurations(c *DpmockV1alpha1Client, namespace string) *nodeResourceConfigurations {
	return &nodeResourceConfigurations{
		gentype.NewClientWithList[*dpmockv1alpha1.NodeResourceConfiguration, *dpmockv1alpha1.NodeResourceConfigurationList](
			"noderesourceconfigurations",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *dpmockv1alpha1.NodeResourceConfiguration { return &dpmockv1alpha1.NodeResourceConfiguration{} },
			func() *dpmockv1alpha1.NodeResourceConfigurationList {
				return &dpmockv1alpha1.NodeResourceConfigurationList{}
			},
		),
	}
}
