//go:build !ignore_autogenerated

/*
Copyright 2025 The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceIDFormat) DeepCopyInto(out *DeviceIDFormat) {
	*out = *in
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceIDFormat.
func (in *DeviceIDFormat) DeepCopy() *DeviceIDFormat {
	if in == nil {
		return nil
	}
	out := new(DeviceIDFormat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceIDGeneratePolicy) DeepCopyInto(out *DeviceIDGeneratePolicy) {
	*out = *in
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(PrefixGeneratePolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceIDGeneratePolicy.
func (in *DeviceIDGeneratePolicy) DeepCopy() *DeviceIDGeneratePolicy {
	if in == nil {
		return nil
	}
	out := new(DeviceIDGeneratePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResource) DeepCopyInto(out *NodeResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResource.
func (in *NodeResource) DeepCopy() *NodeResource {
	if in == nil {
		return nil
	}
	out := new(NodeResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeResource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourceConfiguration) DeepCopyInto(out *NodeResourceConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourceConfiguration.
func (in *NodeResourceConfiguration) DeepCopy() *NodeResourceConfiguration {
	if in == nil {
		return nil
	}
	out := new(NodeResourceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeResourceConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourceConfigurationList) DeepCopyInto(out *NodeResourceConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeResourceConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourceConfigurationList.
func (in *NodeResourceConfigurationList) DeepCopy() *NodeResourceConfigurationList {
	if in == nil {
		return nil
	}
	out := new(NodeResourceConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeResourceConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourceConfigurationSpec) DeepCopyInto(out *NodeResourceConfigurationSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ResourceRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourceConfigurationSpec.
func (in *NodeResourceConfigurationSpec) DeepCopy() *NodeResourceConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(NodeResourceConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourceConfigurationStatus) DeepCopyInto(out *NodeResourceConfigurationStatus) {
	*out = *in
	if in.ResourceDescriptions != nil {
		in, out := &in.ResourceDescriptions, &out.ResourceDescriptions
		*out = make([]ResourceDescription, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourceConfigurationStatus.
func (in *NodeResourceConfigurationStatus) DeepCopy() *NodeResourceConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(NodeResourceConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourceList) DeepCopyInto(out *NodeResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourceList.
func (in *NodeResourceList) DeepCopy() *NodeResourceList {
	if in == nil {
		return nil
	}
	out := new(NodeResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourceSpec) DeepCopyInto(out *NodeResourceSpec) {
	*out = *in
	if in.DeviceIDGeneratePolicy != nil {
		in, out := &in.DeviceIDGeneratePolicy, &out.DeviceIDGeneratePolicy
		*out = new(DeviceIDGeneratePolicy)
		(*in).DeepCopyInto(*out)
	}
	out.DefaultCapacity = in.DefaultCapacity.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourceSpec.
func (in *NodeResourceSpec) DeepCopy() *NodeResourceSpec {
	if in == nil {
		return nil
	}
	out := new(NodeResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourceStatus) DeepCopyInto(out *NodeResourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourceStatus.
func (in *NodeResourceStatus) DeepCopy() *NodeResourceStatus {
	if in == nil {
		return nil
	}
	out := new(NodeResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrefixGeneratePolicy) DeepCopyInto(out *PrefixGeneratePolicy) {
	*out = *in
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = make(StaticPrefixGeneratePolicy, len(*in))
		copy(*out, *in)
	}
	if in.ParentResourceRef != nil {
		in, out := &in.ParentResourceRef, &out.ParentResourceRef
		*out = new(ResourceReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrefixGeneratePolicy.
func (in *PrefixGeneratePolicy) DeepCopy() *PrefixGeneratePolicy {
	if in == nil {
		return nil
	}
	out := new(PrefixGeneratePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceBasicDescription) DeepCopyInto(out *ResourceBasicDescription) {
	*out = *in
	out.Capacity = in.Capacity.DeepCopy()
	in.DeviceIDFormat.DeepCopyInto(&out.DeviceIDFormat)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceBasicDescription.
func (in *ResourceBasicDescription) DeepCopy() *ResourceBasicDescription {
	if in == nil {
		return nil
	}
	out := new(ResourceBasicDescription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceDescription) DeepCopyInto(out *ResourceDescription) {
	*out = *in
	in.ResourceBasicDescription.DeepCopyInto(&out.ResourceBasicDescription)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceDescription.
func (in *ResourceDescription) DeepCopy() *ResourceDescription {
	if in == nil {
		return nil
	}
	out := new(ResourceDescription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceInfo) DeepCopyInto(out *ResourceInfo) {
	*out = *in
	if in.ResourceRef != nil {
		in, out := &in.ResourceRef, &out.ResourceRef
		*out = new(ResourceReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceInfo.
func (in *ResourceInfo) DeepCopy() *ResourceInfo {
	if in == nil {
		return nil
	}
	out := new(ResourceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceReference) DeepCopyInto(out *ResourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReference.
func (in *ResourceReference) DeepCopy() *ResourceReference {
	if in == nil {
		return nil
	}
	out := new(ResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequirement) DeepCopyInto(out *ResourceRequirement) {
	*out = *in
	in.ResourceInfo.DeepCopyInto(&out.ResourceInfo)
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequirement.
func (in *ResourceRequirement) DeepCopy() *ResourceRequirement {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in StaticPrefixGeneratePolicy) DeepCopyInto(out *StaticPrefixGeneratePolicy) {
	{
		in := &in
		*out = make(StaticPrefixGeneratePolicy, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticPrefixGeneratePolicy.
func (in StaticPrefixGeneratePolicy) DeepCopy() StaticPrefixGeneratePolicy {
	if in == nil {
		return nil
	}
	out := new(StaticPrefixGeneratePolicy)
	in.DeepCopyInto(out)
	return *out
}
