apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "volcano-deviceplugin-mock.controller.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "volcano-deviceplugin-mock.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "volcano-deviceplugin-mock.controller.name" . }}
  labels:
    {{- include "volcano-deviceplugin-mock.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "volcano-deviceplugin-mock.controller.name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "volcano-deviceplugin-mock.controller.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "volcano-deviceplugin-mock.controller.name" . }}
  labels:
    {{- include "volcano-deviceplugin-mock.labels" . | nindent 4 }}
rules:
  # permissions to do leader election.
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "create", "patch" ]
  # permissions to reconcile.
  - apiGroups: [ "dpmock.volcano.sh" ]
    resources: [ "noderesourceconfigurations" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "dpmock.volcano.sh" ]
    resources: [ "noderesourceconfigurations/finalizers" ]
    verbs: [ "update" ]
  - apiGroups: [ "dpmock.volcano.sh" ]
    resources: [ "noderesourceconfigurations/status" ]
    verbs: [ "get", "update", "patch" ]
  - apiGroups: [ "dpmock.volcano.sh" ]
    resources: [ "noderesources" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "list", "watch", "update", "patch" ]
