apiVersion: dpmock.volcano.sh/v1alpha1
kind: NodeResource
metadata:
  name: nvidia-gpu
spec:
  resourceName: nvidia.com/gpu
  deviceIDGeneratePolicy:
    prefix:
      static:
        - nvidia
    delimiter: ""
    ordinalStart: 0
---
apiVersion: dpmock.volcano.sh/v1alpha1
kind: NodeResource
metadata:
  name: volcano-xgpu-core
spec:
  resourceName: volcano.sh/gpu-core.percentage
  deviceIDGeneratePolicy:
    prefix:
      parentResourceRef:
        apiGroup: dpmock.volcano.sh
        kind: NodeResource
        name: nvidia-gpu
    delimiter: "-"
    ordinalStart: 0
  defaultCapacity: 100
---
apiVersion: dpmock.volcano.sh/v1alpha1
kind: NodeResource
metadata:
  name: volcano-xgpu-mem
spec:
  resourceName: volcano.sh/gpu-mem.128Mi
  deviceIDGeneratePolicy:
    prefix:
      parentResourceRef:
        apiGroup: dpmock.volcano.sh
        kind: NodeResource
        name: nvidia-gpu
    delimiter: "-"
    ordinalStart: 0
  defaultNodePatchTemplate: |
    metadata:
      annotations:{{ `
        device-status.volcano.sh/nvidia: '{{ toJson .deviceIDFormat.prefix }}'` }}
  defaultNodeUndoPatch: |
    metadata:
      annotations:
        device-status.volcano.sh/nvidia: null
---
apiVersion: dpmock.volcano.sh/v1alpha1
kind: NodeResource
metadata:
  name: ascend-d910a
spec:
  resourceName: huawei.com/ascend-1980
  deviceIDGeneratePolicy:
    prefix:
      static:
        - davinci
    delimiter: ""
    ordinalStart: 0
  defaultNodePatchTemplate: |
    metadata:
      annotations:{{ `
        {{- $num_list := atoi .capacity | until }}
        {{- $hccs_list := list }}
        {{- range $i, $e := chunk 4 $num_list }}
        {{- $hccs_list = join "," $e | append $hccs_list }}
        {{- end }}
        volcano.sh/device-topologys: '{"topologys":[{"type":"HCCS","groups":{{ toJson $hccs_list }}}]}'` }}
  defaultNodeUndoPatch: |
    metadata:
      annotations:
        volcano.sh/device-topologys: null
---
apiVersion: dpmock.volcano.sh/v1alpha1
kind: NodeResource
metadata:
  name: ascend-d910b
spec:
  resourceName: huawei.com/ascend-1980
  deviceIDGeneratePolicy:
    prefix:
      static:
        - davinci
    delimiter: ""
    ordinalStart: 0
  defaultNodePatchTemplate: |
    metadata:
      annotations:{{ `
        {{- $num_list := atoi .capacity | until }}
        {{- $hccs_list := join "," $num_list | list }}
        volcano.sh/device-topologys: '{"topologys":[{"type":"HCCS","groups":{{ toJson $hccs_list }}}]}'` }}
  defaultNodeUndoPatch: |
    metadata:
      annotations:
        volcano.sh/device-topologys: null
---
apiVersion: dpmock.volcano.sh/v1alpha1
kind: NodeResource
metadata:
  name: ascend-d910c
spec:
  resourceName: huawei.com/ascend-1980
  deviceIDGeneratePolicy:
    prefix:
      static:
        - davinci
    delimiter: ""
    ordinalStart: 0
  defaultNodePatchTemplate: |
    metadata:
      annotations:{{ `
        {{- $num_list := atoi .capacity | until }}
        {{- $hccs_list := join "," $num_list | list }}
        {{- $sio_list := list }}
        {{- range $i, $e := chunk 2 $num_list }}
        {{- $sio_list = join "," $e | append $sio_list }}
        {{- end }}
        volcano.sh/device-topologys: '{"topologys":[{"type":"HCCS","groups":{{ toJson $hccs_list }}},{"type":"SIO","groups":{{ toJson $sio_list }}}]}'` }}
  defaultNodeUndoPatch: |
    metadata:
      annotations:
        volcano.sh/device-topologys: null
---
apiVersion: dpmock.volcano.sh/v1alpha1
kind: NodeResource
metadata:
  name: ascend-d310
spec:
  resourceName: huawei.com/ascend-310
  deviceIDGeneratePolicy:
    prefix:
      static:
        - davinci
    delimiter: ""
    ordinalStart: 0
  defaultNodePatchTemplate: |
    metadata:
      annotations:
        volcano.sh/device-topologys: null
  defaultNodeUndoPatch: |
    metadata:
      annotations:
        volcano.sh/device-topologys: null
---
apiVersion: dpmock.volcano.sh/v1alpha1
kind: NodeResource
metadata:
  name: ascend-d310p
spec:
  resourceName: huawei.com/ascend-310
  deviceIDGeneratePolicy:
    prefix:
      static:
        - davinci
    delimiter: ""
    ordinalStart: 0
  defaultNodePatchTemplate: |
    metadata:
      annotations:{{ `
        {{- $num_list := atoi .capacity | until }}
        {{- $hccs_list := list }}
        {{- range $i, $e := chunk 16 $num_list }}
        {{- $hccs_list = join "," $e | append $hccs_list }}
        {{- end }}
        {{- $sio_list := list }}
        {{- range $i, $e := chunk 2 $num_list }}
        {{- $sio_list = join "," $e | append $sio_list }}
        {{- end }}
        volcano.sh/device-topologys: '{"topologys":[{"type":"HCCS","groups":{{ toJson $hccs_list }}},{"type":"SIO","groups":{{ toJson $sio_list }}}]}'` }}
  defaultNodeUndoPatch: |
    metadata:
      annotations:
        volcano.sh/device-topologys: null
