/*
Copyright 2025 The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	apidpmockv1alpha1 "volcano.sh/deviceplugin-mock/api/dpmock/v1alpha1"
	versioned "volcano.sh/deviceplugin-mock/client-go/clientset/versioned"
	internalinterfaces "volcano.sh/deviceplugin-mock/client-go/informers/externalversions/internalinterfaces"
	dpmockv1alpha1 "volcano.sh/deviceplugin-mock/client-go/listers/dpmock/v1alpha1"
)

// NodeResourceConfigurationInformer provides access to a shared informer and lister for
// NodeResourceConfigurations.
type NodeResourceConfigurationInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() dpmockv1alpha1.NodeResourceConfigurationLister
}

type nodeResourceConfigurationInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewNodeResourceConfigurationInformer constructs a new informer for NodeResourceConfiguration type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNodeResourceConfigurationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNodeResourceConfigurationInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredNodeResourceConfigurationInformer constructs a new informer for NodeResourceConfiguration type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNodeResourceConfigurationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DpmockV1alpha1().NodeResourceConfigurations(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DpmockV1alpha1().NodeResourceConfigurations(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DpmockV1alpha1().NodeResourceConfigurations(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DpmockV1alpha1().NodeResourceConfigurations(namespace).Watch(ctx, options)
			},
		},
		&apidpmockv1alpha1.NodeResourceConfiguration{},
		resyncPeriod,
		indexers,
	)
}

func (f *nodeResourceConfigurationInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNodeResourceConfigurationInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *nodeResourceConfigurationInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apidpmockv1alpha1.NodeResourceConfiguration{}, f.defaultInformer)
}

func (f *nodeResourceConfigurationInformer) Lister() dpmockv1alpha1.NodeResourceConfigurationLister {
	return dpmockv1alpha1.NewNodeResourceConfigurationLister(f.Informer().GetIndexer())
}
